cargo-features = ["edition"]

[package]
name = "example-app"
version = "0.1.0"
authors = ["steveklabnik <steve@steveklabnik.com>"]
edition = "2018"

[dependencies.sparkles]
path = "../sparkles"

[dependencies.sparkles-macros]
path = "../sparkles-macros"